# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f608915cc2610b0891769fe917963de72ecfe27ced125e28fc260e5642db187d695ab9e9d4a8ebfacf9352f489d1d54142d081ee523afbb43d602737c29086ca

test:
  secret_key_base: 417b56cdf4d90271ca1a377e72d28221adfb634395195c3063986dec71c99c3dd3578928e49c7c584b3200ef1dc7863c491721b0e6e9d20b7e5f4683c949f7b1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
